default: &default
  adapter: sqlite3
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: db/development.sqlite3
  pool: 5

test:
  <<: *default
  database: db/test.sqlite3

production:
  url: <%= ENV['DATABASE_URL'] %>
